### ISSUE TITLE
Command 'breakingnews' raised an exception: NotImplementedError: 

### ISSUE THREAD

**Issue by xenton76** [reticivis-net/mediaforge#267] opened 2024-10-28 01:45 UTC
### Describe the bug

somehow it failed

### Traceback

[traceback.txt](https://github.com/user-attachments/files/17536321/traceback.txt)

### Expected Behavior

i expected a breaking news caption

### Steps To Reproduce

1. run the command 2. see the error

**Comment by reticivis-net** [comment] 2024-10-28 04:45
Duplicate of #133

**Closed** 2024-10-28 04:46 UTC
Labels: duplicate, not a bug
