### ISSUE TITLE
Expected image, <function mp4togif at 0x7efcdd5cc540> returned nothing.

### ISSUE THREAD

**Issue by javolinlake** [reticivis-net/mediaforge#232] opened 2024-02-16 17:48 UTC
### Describe the bug

tried to use $togif on a shortened version of a video and it didn't work.

### Traceback

DATETIME:2024-02-16 17:42:47.146137 COMMAND:$togif TRACEBACK: Traceback (most recent call last): File "/root/.cache/pypoetry/virtualenvs/mediaforge-HXFskkj--py3.12/lib/python3.12/site-packages/discord/ext/commands/core.py", line 235, in wrapped ret = await coro(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/mediaforge/src/commands/conversion.py", line 146, in togif await process(ctx, processing.ffmpeg.mp4togif, [["VIDEO"]]) File "/mediaforge/src/core/process.py", line 151, in process raise e File "/mediaforge/src/core/process.py", line 125, in process raise processing.common.ReturnedNothing(f"Expected image, {func} returned nothing.") processing.common.ReturnedNothing: Expected image, <function mp4togif at 0x7efcdd5cc540> returned nothing.

**Comment by reticivis-net** [comment] 2024-09-15 22:17
duplicate of #208

**Closed by reticivis-net** 2024-09-15 22:17 UTC
Labels: bug
