### ISSUE TITLE
Command Togif didn't work, no return 

### ISSUE THREAD

**Issue by Asuna-Yuuki69** [reticivis-net/mediaforge#208] opened 2023-09-08 08:53 UTC
### Describe the bug

After using Togif command, it downloaded the video and "processed" after a while it thrown error with no output 

### Traceback
```
DATETIME:2023-09-08 08:47:55.423182
COMMAND:/togif {}
TRACEBACK:
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/mediaforge-HXFskkj--py3.11/lib/python3.11/site-packages/discord/app_commands/commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mediaforge/src/commands/conversion.py", line 146, in togif
    await process(ctx, processing.ffmpeg.mp4togif, [["VIDEO"]])
  File "/mediaforge/src/core/process.py", line 151, in process
    raise e
  File "/mediaforge/src/core/process.py", line 125, in process
    raise processing.common.ReturnedNothing(f"Expected image, {func} returned nothing.")
processing.common.ReturnedNothing: Expected image, <function mp4togif at 0x7f32759dbec0> returned nothing.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/mediaforge-HXFskkj--py3.11/lib/python3.11/site-packages/discord/ext/commands/hybrid.py", line 438, in _invoke_with_namespace
    value = await self._do_call(ctx, ctx.kwargs)  # type: ignore
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/mediaforge-HXFskkj--py3.11/lib/python3.11/site-packages/discord/app_commands/commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'togif' raised an exception: ReturnedNothing: Expected image, <function mp4togif at 0x7f32759dbec0> returned nothing.
```

### Expected Behavior

It will convert my mp4 video to a gif 

### Steps To Reproduce

Send mp4 video 

### Anything Else

:eemark: `discord.app_commands.errors.CommandInvokeError: Hybrid command raised an error: Command 'togif' raised an exception: ReturnedNothing: Expected image, <function mp4togif at 0x7f32759dbec0> returned nothing.`

**Comment by HexCodeFFF** [comment] 2023-10-28 20:18
Does this always happen on a certian gif or is it random?

**Comment by Asuna-Yuuki69** [comment] 2023-10-30 21:15
> Does this always happen on a certian gif or is it random?

Yuh, I just tried different vids and whenever it's supposed to convert it, it spits out the same error, the video was 15s long.

**Comment by Asuna-Yuuki69** [comment] 2023-10-30 21:17
Yet esmbot which I'm not sure is owned by you, is able to convert images to gif format easily. Mediaforge just has these problems with mp4 vids, also the :working: emoji is displayed as ":working:" instead of an actual emoji

**Comment by HexCodeFFF** [comment] 2023-10-30 21:19
> Yet esmbot which I'm not sure is owned by you, is able to convert images to gif format easily.

Esmbot is not owned by me and uses a completely different internal system

> also the :working: emoji is displayed as ":working:" instead of an actual emoji

Probably beccause it doesn't have external emoji perms in the server it's in. i should implement something to detect that

**Comment by HexCodeFFF** [comment] 2023-10-30 21:22
Can you send me one of the videos? I'm unable to reproduce the error.

**Comment by Asuna-Yuuki69** [comment] 2023-10-30 22:24
> Can you send me one of the videos? I'm unable to reproduce the error.

Sure, just be aware that they may seem pretty unusual at least 

[vid1](https://cdn.discordapp.com/attachments/784733312501153804/1164481098311544862/3F11D04F-BCA0-474D-9088-A1B34EEBA80C.mov?ex=654c9908&is=653a2408&hm=62c96ed1678db601f139d6d2995b689e3d820fd3b549b4257d6262fe1b93a06f&)

[vid2](https://cdn.discordapp.com/attachments/784733312501153804/1168659187883061249/Snapinsta.app_video_374386133_205676962515820_1838976584715330062_n.mov?ex=655291af&is=65401caf&hm=fa84a20ff6a9d866895ab2f04906215430b9068eefe6947f38bd0db55756ba65&)

These two were used to make them into a gif

**Comment by reticivis-net** [comment] 2024-09-15 22:07
can you send those videos again, the links are brokey

**Comment by reticivis-net** [comment] 2024-09-15 22:14
ok well both of those videos, when converted to gifs, are over 100MB so the bot aborts, but it seems to work, so I'm closing this issue. reopen if it happens again

**Closed by reticivis-net** 2024-09-15 22:14 UTC
Labels: bug, unable to reproduce
