### ISSUE TITLE
discord.app_commands.errors.CommandInvokeError: Hybrid command raised an error: Command 'breakingnews' raised an exception: NotImplementedError: 

### ISSUE THREAD

**Issue by 24flopp** [reticivis-net/mediaforge#246] opened 2024-06-27 16:25 UTC
### Describe the bug

spits out an error when you run /breakingnews

### Traceback

DATETIME:2024-06-27 16:23:03.620329
COMMAND:/breakingnews {'caption': 'a'}
TRACEBACK:
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/mediaforge-HXFskkj--py3.12/lib/python3.12/site-packages/discord/app_commands/commands.py", line 857, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mediaforge/src/commands/caption.py", line 87, in breakingnews
    raise NotImplementedError  # TODO: implement
    ^^^^^^^^^^^^^^^^^^^^^^^^^
NotImplementedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/mediaforge-HXFskkj--py3.12/lib/python3.12/site-packages/discord/ext/commands/hybrid.py", line 444, in _invoke_with_namespace
    value = await self._do_call(ctx, ctx.kwargs)  # type: ignore
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/mediaforge-HXFskkj--py3.12/lib/python3.12/site-packages/discord/app_commands/commands.py", line 876, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'breakingnews' raised an exception: NotImplementedError: 

### Expected Behavior

Create a fake "Breaking News" screencap

### Steps To Reproduce

1. Use the /breakingnews command
2. See error

**Comment by reticivis-net** [comment] 2024-06-27 20:09
Duplicate of #133

**Closed** 2024-06-27 20:09 UTC
Labels: bug, duplicate
