### ISSUE TITLE
Command 'breakingnews' raised an exception: NotImplementedError: 

### ISSUE THREAD

**Issue by dragonfly-TIFF** [reticivis-net/mediaforge#247] opened 2024-07-10 22:41 UTC
### Describe the bug

DATETIME:2024-07-10 22:38:45.776694
COMMAND:/breakingnews {'caption': 'Life is tough!'}

discord.app_commands.errors.CommandInvokeError: Hybrid command raised an error: Command 'breakingnews' raised an exception: NotImplementedError: 

### Traceback

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/mediaforge-HXFskkj--py3.12/lib/python3.12/site-packages/discord/app_commands/commands.py", line 857, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mediaforge/src/commands/caption.py", line 87, in breakingnews
    raise NotImplementedError  # TODO: implement
    ^^^^^^^^^^^^^^^^^^^^^^^^^
NotImplementedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/mediaforge-HXFskkj--py3.12/lib/python3.12/site-packages/discord/ext/commands/hybrid.py", line 444, in _invoke_with_namespace
    value = await self._do_call(ctx, ctx.kwargs)  # type: ignore
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/mediaforge-HXFskkj--py3.12/lib/python3.12/site-packages/discord/app_commands/commands.py", line 876, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'breakingnews

### Expected Behavior

return breaking news image with caption entered

**Comment by reticivis-net** [comment] 2024-09-15 22:29
duplicate of #133

**Closed by reticivis-net** 2024-09-15 22:29 UTC
Labels: bug
