### ISSUE TITLE
Command 'help' raised an exception: HTTPException: 400 Bad Request (error code: 50035): Invalid Form BodyIn data.embeds.0.fields: Must be 25 or fewer in length.

### ISSUE THREAD

**Issue by notMEEPoffaith** [reticivis-net/mediaforge#239] opened 2024-03-26 15:58 UTC
### Describe the bug

it just doesnt let me do "/help editing"

### Traceback

[traceback.txt](https://github.com/reticivis-net/mediaforge/files/14761214/traceback.txt)

### Expected Behavior

it shows the commands for the editing category

### Steps To Reproduce

1. do /help editing or $help editing

**Comment by reticivis-net** [comment] 2024-03-26 17:37
Duplicate of #230

**Closed by reticivis-net** 2024-03-26 17:37 UTC
Labels: bug
