### ISSUE TITLE
cannot pickle '_io.BufferedReader' object

### ISSUE THREAD

**Issue by ExpiredGummy** [reticivis-net/mediaforge#218] opened 2023-11-26 02:27 UTC
### Describe the bug

tried downloading a video with mediaforge but i guess it didnt work??

### Traceback

[traceback.txt](https://github.com/HexCodeFFF/mediaforge/files/13465750/traceback.txt)

### Expected Behavior

To download the video

**Comment by reticivis-net** [comment] 2024-01-10 06:38
duplicate of #209

**Closed by reticivis-net** 2024-01-10 06:38 UTC
Labels: bug
