### ISSUE TITLE
Command 'togif' raised an exception: ReturnedNothing: Expected image, <function mp4togif at 0x7fc42660c540> returned nothing.

### ISSUE THREAD

**Issue by chickenbutt1** [reticivis-net/mediaforge#233] opened 2024-02-23 05:23 UTC
### Describe the bug

wont work 

### Traceback

DATETIME:2024-02-23 05:20:16.354795
COMMAND:/togif {}
TRACEBACK:
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/mediaforge-HXFskkj--py3.12/lib/python3.12/site-packages/discord/app_commands/commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mediaforge/src/commands/conversion.py", line 146, in togif
    await process(ctx, processing.ffmpeg.mp4togif, [["VIDEO"]])
  File "/mediaforge/src/core/process.py", line 151, in process
    raise e
  File "/mediaforge/src/core/process.py", line 125, in process
    raise processing.common.ReturnedNothing(f"Expected image, {func} returned nothing.")
processing.common.ReturnedNothing: Expected image, <function mp4togif at 0x7fc42660c540> returned nothing.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/mediaforge-HXFskkj--py3.12/lib/python3.12/site-packages/discord/ext/commands/hybrid.py", line 438, in _invoke_with_namespace
    value = await self._do_call(ctx, ctx.kwargs)  # type: ignore
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/mediaforge-HXFskkj--py3.12/lib/python3.12/site-packages/discord/app_commands/commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'togif' raised an exception: ReturnedNothing: Expected image, <function mp4togif at 0x7fc42660c540> returned nothing.

### Expected Behavior

i expected it to make a funny gif

### Steps To Reproduce

send this: https://cdn.discordapp.com/attachments/1128478850322550784/1210455162850775110/kuhuyUrc.mp4?ex=65ea9f37&is=65d82a37&hm=ba6e511f8e0b4219d0991a274c9850b5ccb93a0d83c13d8f0609a8ebe7b87629&
wait 7 minutes
and then it wags my finger at me

### Anything Else

discord smirk cat emoji

**Comment by reticivis-net** [comment] 2024-09-15 22:20
duplicate of #208

**Closed by reticivis-net** 2024-09-15 22:20 UTC
Labels: bug
