### ISSUE TITLE
cannot pickle '_io.BufferedReader' object

### ISSUE THREAD

**Issue by Bruhman69420XD** [reticivis-net/mediaforge#219] opened 2023-11-26 22:17 UTC
### Describe the bug

video downloading not working

### Traceback

[traceback.txt](https://github.com/HexCodeFFF/mediaforge/files/13468214/traceback.txt)

**Comment by reticivis-net** [comment] 2024-01-10 06:39
duplicate of #209

**Closed by reticivis-net** 2024-01-10 06:39 UTC
Labels: bug
