### ISSUE TITLE
TypeError: Command raised an exception: TypeError: cannot pickle '_io.BufferedReader' object

### ISSUE THREAD

**Issue by ClovekNeznamy** [reticivis-net/mediaforge#222] opened 2023-11-28 09:06 UTC
### Describe the bug

Bot won't download the vid from yt

### Traceback

[traceback-2.txt](https://github.com/HexCodeFFF/mediaforge/files/13485785/traceback-2.txt)

### Expected Behavior

To be able to download a vid from yt

### Steps To Reproduce

$dl link from yt
<:eemark:803791399710883871> `TypeError: Command raised an exception: TypeError: cannot pickle '_io.BufferedReader' object`
The end

### Anything Else

![Screenshot_20231128_100447_Discord](https://github.com/HexCodeFFF/mediaforge/assets/96877325/b3bc70df-0d38-4229-814f-327ae69042ac)

**Comment by reticivis-net** [comment] 2024-01-10 06:40
duplicate of #209

**Closed by reticivis-net** 2024-01-10 06:40 UTC
Labels: bug
