### ISSUE TITLE
Command 'videodl' raised an exception: TypeError: cannot pickle 'BufferedReader' instances

### ISSUE THREAD

**Issue by joindr** [reticivis-net/mediaforge#226] opened 2024-01-09 14:14 UTC
### Describe the bug

Trying to upload a video so i can download it

### Traceback

[traceback.txt](https://github.com/reticivis-net/mediaforge/files/13874797/traceback.txt)

### Expected Behavior

The video to be able to be downloaded.

### Steps To Reproduce

/video videourl:https://youtube.com/shorts/agP6hLkFyBw?si=AAP4HcG6uiwwW4hO then it happened.

### Anything Else

Nothing else

**Comment by reticivis-net** [comment] 2024-01-10 06:39
duplicate of #209

**Closed by reticivis-net** 2024-01-10 06:39 UTC
Labels: bug, duplicate
