### ISSUE TITLE
cannot pickle '_io.BufferedReader' object

### ISSUE THREAD

**Issue by dotthinh** [reticivis-net/mediaforge#221] opened 2023-11-28 04:17 UTC
### Describe the bug

I cant dowload yotube video

### Traceback

[traceback.txt](https://github.com/HexCodeFFF/mediaforge/files/13483369/traceback.txt)

### Expected Behavior

Fix

**Comment by reticivis-net** [comment] 2024-01-10 06:39
duplicate of #209

**Closed by reticivis-net** 2024-01-10 06:39 UTC
Labels: bug
